services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./runtime/redis-data:/data
    command: >
      redis-server
      --replicaof no one
      --slave-read-only no
    environment:
      - REDIS_DATABASES=16
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./runtime/mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=wNKvCILsDJ
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --bind-address=0.0.0.0
    hostname: mysql

# Models in service

  shared-models:
    build:
      context: ./shared_models
      dockerfile: Dockerfile
    image: telegram-parser-api-python-with-shared-models:latest

# Services

  api:
    ports:
      - "6000:6000"
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        IMAGE_WITH_MODELS: telegram-parser-api-python-with-shared-models:latest
    depends_on:
      - shared-models
      - redis
      - mysql
    restart: always
    environment:
      - SERVER_PORT=6000
    env_file:
      - .env
  
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        IMAGE_WITH_MODELS: telegram-parser-api-python-with-shared-models:latest
    depends_on:
      - shared-models
      - redis
      - mysql
    restart: always
    environment:
      - MAX_JOBS=100
      - MYSQL_URL=mysql://channels:channels_password@mysql:3306/channels_db
      - WORKERS_COUNT=1
    env_file:
      - .env
  
  parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
      args:
        IMAGE_WITH_MODELS: telegram-parser-api-python-with-shared-models:latest
    depends_on:
      - shared-models
      - redis
      - mysql
      - database
    restart: always
    environment:
      - MAX_JOBS=5
      - MYSQL_URL=mysql://telegram:telegram_password@mysql:3306/telegram_db
      - WORKERS_COUNT=2
    env_file:
      - .env
  
  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile
      args:
        IMAGE_WITH_MODELS: telegram-parser-api-python-with-shared-models:latest
    depends_on:
      - shared-models
      - redis
    restart: always
    environment:
      - MAX_JOBS=10
    env_file:
      - .env
  
  storage:
    build:
      context: ./storage
      dockerfile: Dockerfile
      args:
        IMAGE_WITH_MODELS: telegram-parser-api-python-with-shared-models:latest
    depends_on:
      - shared-models
      - redis
      - mysql
    restart: always
    environment:
      - MAX_JOBS=10
    env_file:
      - .env
  
  
  